name: 'Set up Golang'
inputs:
  go-version:
    description: "The version of node to use"
    required: false
    type: string
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: "⬇️ Checkout"
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      name: 🔧 Set up Node.js
      with:
        node-version: 'latest'
    - uses: actions/setup-go@v5
      name: 🔧 Set up Go ${{ inputs.go-version }}
      with:
        go-version: ${{ inputs.go-version }}
    - name: 📦 Install dependencies
      shell: bash
      run: |
        go get .
        go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
        npm install semantic-release semantic-release-export-data @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec @semantic-release/commit-analyzer @semantic-release/release-notes-generator
